from enum import Enum, EnumMeta


class CustomEnumMeta(EnumMeta):
    def __getitem__(cls, name):
        try:
            return super().__getitem__(name)
        except KeyError:
            # print(f"Missing name: {name}")  # Handle the missing name case
            return cls.OTHER  # Fallback value


class GedcomTag(Enum, metaclass=CustomEnumMeta):
    ABBR = "Abbreviation"
    ADDR = "Address"
    ADOP = "Adoption"
    ADR1 = "Address Line 1"
    ADR2 = "Address Line 2"
    ADR3 = "Address Line 3"
    AFN = "Ancestral File Number"
    AGE = "Age"
    ANCE = "Ancestors"
    ANCI = "Ancestor Interest"
    ANUL = "Annulment"
    AUTH = "Author"
    BAPL = "LDS Baptism"
    BAPM = "Baptism"
    BARM = "Bar Mitzvah"
    BASM = "Bas Mitzvah"
    BIRT = "Birth"
    BLES = "Blessing"
    BLOB = "Binary Object"
    BURI = "Burial"
    CALN = "Call Number"
    CAST = "Caste"
    CAUS = "Cause of Death"
    CENS = "Census"
    CHAR = "Character Set"
    CHIL = "Child"
    CHR = "Christening"
    CHRA = "Adult Christening"
    CITY = "City"
    CONC = "Concatenation"
    CONF = "Confirmation"
    CONL = "LDS Confirmation"
    CORP = "Corporation"
    CREM = "Cremation"
    CTRY = "Country"
    DATA = "Data"
    DATE = "Date"
    DEAT = "Death"
    DESC = "Descent"
    DESI = "Descendant Interest"
    DEST = "Destination"
    DIV = "Divorce"
    DIVF = "Divorce Filed"
    DSCR = "Description"
    EDUC = "Education"
    EMAIL = "Email"
    EMIG = "Emigration"
    ENDL = "LDS Endowment"
    ENGA = "Engagement"
    EVEN = "Event"
    FACT = "Fact"
    FAM = "Family"
    FAMC = "Family Child"
    FAMS = "Family Spouse"
    FAX = "Fax"
    FCOM = "First Communion"
    FILE = "File"
    FONE = "Phonetic Name"
    FORM = "Format"
    GEDC = "GEDCOM Version"
    GIVN = "Given Name"
    GRAD = "Graduation"
    HEAD = "Header"
    HUSB = "Husband"
    IDNO = "ID Number"
    IMMI = "Immigration"
    INDI = "Individual"
    LANG = "Language"
    LATI = "Latitude"
    LEGA = "Legatee"
    LONG = "Longitude"
    MAP = "Map"
    MARB = "Marriage Bann"
    MARC = "Marriage Contract"
    MARL = "Marriage License"
    MARR = "Marriage"
    MARS = "Marriage Settlement"
    MARV = "Marriage Validation"
    _MEDI = "Media"
    NAME = "Name"
    NATI = "National Origin"
    NATU = "Naturalization"
    NCHI = "Children"
    NICK = "Nickname"
    NMR = "Marriages"
    NOTE = "Note"
    NPFX = "Name Prefix"
    NSFX = "Name Suffix"
    OBJE = "Object"
    OCCU = "Occupation"
    ORDN = "Ordination"
    OTHER = "Other"
    PAGE = "Page"
    PEDI = "Pedigree"
    PHON = "Telephone"
    PLAC = "Place"
    POST = "Postal Code"
    PROB = "Probate"
    PROP = "Possessions"
    PUBL = "Publication"
    QUAY = "Quality of Data"
    REFN = "Reference Number"
    RELA = "Relation"
    RELI = "Religious Affiliation"
    REPO = "Repository"
    RESI = "Residence"
    RESN = "Restriction"
    RETI = "Retirement"
    RIN = "Record ID Number"
    ROLE = "Role"
    ROMN = "Romanized Name"
    SEX = "Sex"
    SLGC = "LDS Child Sealing"
    SLGS = "LDS Spouse Sealing"
    SOUR = "Source"
    SPFX = "Surname Prefix"
    SSN = "SSN"
    STAE = "State"
    SUBM = "Submitter"
    SUBN = "Submission"
    SURN = "Surname"
    TEMP = "LDS Temple"
    TEXT = "Text"
    TIME = "Time"
    TITL = "Title"
    TRLR = "Trailer"
    TYPE = "Type"
    VERS = "Version"
    WAC = "LDS Initiation"
    WIFE = "Wife"
    WILL = "Will"
    WWW = "Web Site"
    _AKA = "Also Known As"
    _ALBUM = "Album"
    _CUTOUT = "Cutout"
    _EXPORTED_FROM_SITE_ID = "Exported From Site ID"
    _FILESIZE = "File Size"
    _MARNM = "Married Name"
    _PARENTPHOTO = "Parent Photo"
    _PARENTRIN = "Parent RIN"
    _PERSONALPHOTO = "Personal Photo"
    _PHOTO_RIN = "Photo RIN"
    _POSITION = "Position"
    _PRIM = "Primary"
    _PRIM_CUTOUT = "Primary Cutout"
    _PRIV = "Private"
    _PROJECT_GUID = "Project GUID"
    _RNAME = "Repository Name"
    _RTLSAVE = "Right-to-Left Save"
    _SOSA = "Sosa Numbering"
    _SOSADABOVILLE = "Sosa d'Aboville Numbering"
    _TYPE = "Source Type"
    _UID = "Unique ID"
    _UPD = "Update"
    _VALID = "Validation"
    _WWW = "Internet Web Site"

    @classmethod
    def _missing_(cls, value):
        # print(f"Missing value: {value[0:100]}")  # only first 100 char
        return cls.OTHER


class Fact:
    def __init__(self, level: int, tag: GedcomTag, value: str) -> None:
        self.tag: GedcomTag = tag
        self.value: str = value
        self.level: int = level
        self.sub_facts: list[Fact] = []  # Details about this Gedcom Tag

    def __str__(self):
        out = f"{self.tag.value}: {self.value}\n"
        for fact in self.sub_facts:
            out += f"\t{fact.tag.value}: {fact.value}\n"

        return out

    def __repr__(self):
        return f"tag={self.tag}, value={self.value}, sub_facts={self.sub_facts}"
